'''
Created on Jun 14, 2012

@author: Administrator
'''
def triangle(n):
    """ euler problem 45
    
    """
    return n*(n+1)//2

def pentagonal(n):
    """ euler problem 44
    Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:
    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    
    >>> pentagonal(5)
    """
    return n*(3*n - 1)//2

def hexagonal(n):
    """euler problem 45
    
    """
    return n*(2*n-1)





if __name__=="__main__":
    import doctest
    doctest.testmod()