'''
Created on Jun 14, 2012

@author: Administrator
'''
import math
def is_integer(x,epsilon=1e-6):
    """Return True if the float x "seems" an integer"""
    return (abs(round(x) - x) < epsilon)

def is_pentagonal(n):
    """ euler problem 44
    Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:
    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    """
    return (n >= 1) and is_integer((1+math.sqrt(1+24*n))/6.0)

def is_pandigital(n):
    """ euler problem 32
    
    We shall say that an n-digit number is pandigital if it makes use of all the digits 1 to n exactly once; 
    for example, the 5-digit number, 15234, is 1 through 5 pandigital.
    >>> is_pandigital(391867254)
    True
    """
    #print(locals())
    return sorted(str(n))==sorted('123456789')

def test():    
    import doctest
    doctest.testmod()
if __name__=="__main__":
    test()
    #print(factors(4648767868))